services:

  python:
    container_name: python
    build: Docker/python
    volumes:
      - ./src:/usr/src/app
      - ./Input:/usr/src/app/Input
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FLASK_ENV: development
    ports:
      - 10001:5000

