services:

  # Database to store template data
  db-template:
    container_name: db-template
    build: Docker/db
    volumes:
      - db-data:/var/lib/postgresql/shared-data/
    ports:
      - "5432:5432"

  python:
    container_name: python
    build: Docker/python
    volumes:
      - ./src:/usr/src/app
      - ./Input:/usr/src/app/Input
    environment:
      USE_DEV_MODE: ${USE_DEV_MODE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db-template
    ports:
      - "8501:8501"

volumes:
  db-data: